services:
  mongodb:
    image: mongo:7
    container_name: cine-stream-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cine-stream-mongo-data:/data/db

volumes:
  cine-stream-mongo-data:
